<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>FinSight.Api</RootNamespace>
    <UserSecretsId>finsight-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinSight.Core\FinSight.Core.csproj" />
    <ProjectReference Include="..\FinSight.Infrastructure\FinSight.Infrastructure.csproj" />
    <ProjectReference Include="..\FinSight.Migrations.Postgres\FinSight.Migrations.Postgres.csproj" />
  </ItemGroup>

</Project>
