using System.Globalization;
using FinSight.Core.Analytics;
using FinSight.Core.Domain;
using FinSight.Infrastructure.Insights;
using FinSight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace FinSight.Infrastructure.Email;

public sealed record DigestCategory(string Name, decimal Amount, decimal? ChangePercent);

public sealed record DigestRecurring(string Merchant, decimal MonthlyAmount);

public sealed record DigestAnomaly(string Merchant, decimal Amount, DateOnly Date);

/// <summary>
/// Everything a monthly summary email says. Every figure comes from <see cref="DashboardService"/>, the same code behind
/// the Overview; nothing is generated by AI except an existing, validated analysis summary. No descriptions, account
/// numbers or email content.
/// </summary>
public sealed record MonthlyDigest(
    DateRange Month,
    string Currency,
    bool HasData,
    decimal Income,
    decimal Spending,
    decimal Net,
    decimal? SavingsRate,
    IReadOnlyList<DigestCategory> TopCategories,
    IReadOnlyList<DigestRecurring> NewRecurring,
    IReadOnlyList<DigestRecurring> EndedRecurring,
    int AnomalyCount,
    DigestAnomaly? BiggestAnomaly,
    int AwaitingUpload,
    int ReadyToImport,
    string? AiSummary)
{
    public string MonthKey => MonthKeyOf(Month.Start);

    public static string MonthKeyOf(DateOnly month) => month.ToString("yyyy-MM", CultureInfo.InvariantCulture);
}

public static class DigestSchedule
{
    /// <summary>Statements for a month arrive a few days after it ends, so a month's summary is due from this day of the next month.</summary>
    public const int SendFromDay = 3;

    /// <summary>The month whose summary is due at <paramref name="now"/> (UTC), or null before the 3rd.</summary>
    public static DateRange? DueMonth(DateTimeOffset now)
    {
        var today = DateOnly.FromDateTime(now.UtcDateTime);
        return today.Day < SendFromDay ? null : PreviousMonth(today);
    }

    public static DateRange PreviousMonth(DateOnly today) => PeriodResolver.Resolve(PeriodPreset.LastMonth, today);
}

/// <summary>Builds a user's monthly summary. Runs in that user's <see cref="UserContext"/>.</summary>
public sealed class DigestBuilder(FinSightDbContext db, DashboardService dashboard, AnalysisService analysis)
{
    private const int TopCategoryCount = 3;
    private const int RecurringListLimit = 3;

    public async Task<MonthlyDigest> BuildAsync(DateRange month, CancellationToken cancellationToken)
    {
        var snapshot = await dashboard.GetSnapshotAsync(month, cancellationToken);
        var summary = snapshot.Summary;
        var currency = snapshot.Settings.Currency;

        var awaitingUpload = await db.Statements.CountAsync(s => s.Status == StatementStatus.AwaitingUpload, cancellationToken);
        var readyToImport = await db.Statements.CountAsync(s => s.Status == StatementStatus.Discovered, cancellationToken);

        if (summary.TransactionCount == 0)
        {
            return new MonthlyDigest(month, currency, false, 0, 0, 0, null, [], [], [], 0, null, awaitingUpload, readyToImport, null);
        }

        // Recurring payments that started or stopped: compare the series active at the end of this month and the one before.
        var previous = await dashboard.GetSnapshotAsync(PeriodResolver.Previous(month), cancellationToken);
        var activeNow = snapshot.Recurring.Where(r => r.IsActive && !r.IsIncome).ToList();
        var activeBefore = previous.Recurring.Where(r => r.IsActive && !r.IsIncome).ToList();
        var newRecurring = activeNow.Where(r => activeBefore.All(b => b.MerchantKey != r.MerchantKey))
            .OrderByDescending(r => r.MonthlyEquivalent).Take(RecurringListLimit)
            .Select(r => new DigestRecurring(r.Merchant, r.MonthlyEquivalent)).ToList();
        var endedRecurring = activeBefore.Where(b => activeNow.All(r => r.MerchantKey != b.MerchantKey))
            .OrderByDescending(r => r.MonthlyEquivalent).Take(RecurringListLimit)
            .Select(r => new DigestRecurring(r.Merchant, r.MonthlyEquivalent)).ToList();

        var biggest = snapshot.Anomalies.OrderByDescending(a => Math.Abs(a.Amount)).FirstOrDefault();

        string? aiSummary = null;
        if (snapshot.Settings.AiInsightsEnabled)
        {
            // Only an analysis generated from exactly this data; a stale one could quote figures that changed.
            var stored = await analysis.GetAsync(month, cancellationToken);
            if (stored is { State: AnalysisState.Fresh, Analysis.Summary: { Length: > 0 } text })
            {
                aiSummary = text;
            }
        }

        return new MonthlyDigest(
            month,
            currency,
            true,
            summary.Income,
            summary.Expenses,
            summary.NetCashFlow,
            summary.SavingsRate,
            summary.Categories.Take(TopCategoryCount).Select(c => new DigestCategory(c.Name, c.Amount, c.ChangePercent)).ToList(),
            newRecurring,
            endedRecurring,
            snapshot.Anomalies.Count,
            biggest is null ? null : new DigestAnomaly(biggest.Merchant, Math.Abs(biggest.Amount), biggest.Date),
            awaitingUpload,
            readyToImport,
            aiSummary);
    }
}
